### PR TITLE
Adding v4.0 of Thermal Curve

### PR DESCRIPTION
**Pull request by mfixstsci**

### CODE REVIEW

**Comment by mfixstsci** [comment]
Wow -- okay looks like the CI is still running python versions that are extremely deprecated 😓 let me make some updates that we should merge in first. Will tag them here.

**Review by bholler — APPROVED** [review]

**Comment by mfixstsci** [comment]
@bholler went ahead and added some updates to the CHANGES file to reflect changes in our next release (v1.3.0)

**Comment by bholler** [comment]
@mfixstsci Did you mean to put "Cycle 3" in the CHANGES file?

**Comment by mfixstsci** [comment]
@bholler HA! See that's what happens when I follow whats in the changes file instead of checking the CfP timeline. I went ahead and updated to cycle 4 😅 I am also going to make one more push when we are ready to release with the date so I can make sure that doesn't happen again.

**Pull request merged**
