### PR TITLE
Update GHA Pipeline

### PR DESCRIPTION
**Pull request by mfixstsci**
- Update python versions
- Update version of checkout action
- Update commands to install and test backgrounds package.

### CODE REVIEW

**Review by bholler — APPROVED** [review]
As long as people can still download and use it, keeping the code together with duct tape and bubblegum seems fine to me.

**Comment by mfixstsci** [comment]
Cool, I am going to ping @zacharyburnett here for the some assistance because I believe that `publish-to-pypi` is deprecated too.

**Comment by zacharyburnett** [comment]
> Cool, I am going to ping @zacharyburnett here for the some assistance because I believe that `publish-to-pypi` is deprecated too.

Yes indeed, I made a PR here to update that: https://github.com/spacetelescope/jwst_backgrounds/pull/29

**Comment by mfixstsci** [comment]
Nice @zacharyburnett I appreciate it!

**Pull request merged**
