### PR TITLE
Add option for plotting calendar date xaxis in plot_bathtub

### PR DESCRIPTION
**Pull request by gbrammer**
Run with `plot_bathtub(showdate=True)`.

### CODE REVIEW

**Comment by pontoppi** [comment]
Cool - I'll test this out soon, probably when I'm back from the proposal workshop.

**Comment by gbrammer** [comment]
I just realized the change does add an astropy dependency, so you can
decide if you want to keep it.

On Tue, Dec 12, 2017 at 2:38 PM, Klaus Pontoppidan <notifications@github.com

**Comment by pontoppi** [comment]
@gbrammer Yeah, I do think we have to be careful adding dependencies for tools that need to be used by people who are not crack python developers. Astropy is not the worst, and I'm guessing that the TVTs already have astropy dependencies. On the other hand, there are already issues with folks messing up their healpy installation...

Maybe there is an easy non-astropy way to create the date, for instance using datetime?

**Comment by gbrammer** [comment]
Closing the pull request as I've added a few other things you won't necessarily want in the public version.

**Comment by pontoppi** [comment]
@gbrammer Just to I understand - you just want to maintain a branch for internal use?

**Comment by gbrammer** [comment]
Hi Klaus,

I think there's no need to keep the branch on the main
spacetelescope/jwst_backgrounds repository, and I'll just push whatever
customizations I want to my own fork (which people are free to use).  For
example I recently added a method to the background class for easy
retrieval of the spectrum itself, along with a feature of manipulating the
spectrum units.  These would require an astropy dependency that you may not
wish to have on the public master branch.

If you want these features, I'd be happy to push them over with a new pull
request.

Gabe

**Pull request closed without merging**
